steps:
  # Docker image oluştur
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/reklam-451421/telegramreklam', '.']

  # Docker image'ı Google Container Registry'ye (GCR) push et
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/reklam-451421/telegramreklam']

  # Cloud Run'a deploy et
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'telegramreklam',
           '--image', 'gcr.io/reklam-451421/telegramreklam',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/reklam-451421/telegramreklam'
